name: Commit Emojis
on:
  [push, pull_request]
jobs:
  change-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for adding emoji to commit messages
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "🍍 "
